# Generated by Django 5.2.8 on 2025-11-18 15:34

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_es", models.CharField(max_length=200, null=True)),
                ("title_de", models.CharField(max_length=200, null=True)),
                ("title_fr", models.CharField(max_length=200, null=True)),
                ("slug", models.SlugField(max_length=200)),
                ("slug_en", models.SlugField(max_length=200, null=True)),
                ("slug_es", models.SlugField(max_length=200, null=True)),
                ("slug_de", models.SlugField(max_length=200, null=True)),
                ("slug_fr", models.SlugField(max_length=200, null=True)),
                ("summary", models.TextField(blank=True)),
                ("summary_en", models.TextField(blank=True, null=True)),
                ("summary_es", models.TextField(blank=True, null=True)),
                ("summary_de", models.TextField(blank=True, null=True)),
                ("summary_fr", models.TextField(blank=True, null=True)),
                ("body", django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name="Body")),
                (
                    "body_en",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Body"
                    ),
                ),
                (
                    "body_es",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Body"
                    ),
                ),
                (
                    "body_de",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Body"
                    ),
                ),
                (
                    "body_fr",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Body"
                    ),
                ),
                (
                    "blocks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Structured block data used by the visual page builder.",
                    ),
                ),
                (
                    "blocks_en",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Structured block data used by the visual page builder.",
                        null=True,
                    ),
                ),
                (
                    "blocks_es",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Structured block data used by the visual page builder.",
                        null=True,
                    ),
                ),
                (
                    "blocks_de",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Structured block data used by the visual page builder.",
                        null=True,
                    ),
                ),
                (
                    "blocks_fr",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Structured block data used by the visual page builder.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Needs review"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="If disabled the page stays in drafts and is hidden from navigation.",
                    ),
                ),
                ("navigation_order", models.PositiveIntegerField(default=0)),
                (
                    "show_navigation_bar",
                    models.BooleanField(
                        default=True, help_text="Display the navigation bar on this page."
                    ),
                ),
                (
                    "custom_nav_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered list of page slugs to display when this page renders (leave empty to hide the navigation bar).",
                    ),
                ),
                ("hero_image", models.ImageField(blank=True, null=True, upload_to="pages/heroes/")),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "render_body_only",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, ignore the block builder and render the raw HTML body only.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pages_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pages_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("navigation_order", "title"),
            },
        ),
    ]
