# Generated by Django 5.2.8 on 2025-11-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='If disabled page stays in drafts and is hidden from navigation.'),
        ),
        migrations.AlterField(
            model_name='page',
            name='render_body_only',
            field=models.BooleanField(default=False, help_text='If enabled, ignore block builder and render raw HTML body only.'),
        ),
        migrations.AlterField(
            model_name='page',
            name='show_navigation_bar',
            field=models.BooleanField(default=True, help_text='Display navigation bar on this page.'),
        ),
    ]
