# Generated by Django 5.2.8 on 2025-11-18 15:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="POSQuickButton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=40)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("PERCENT", "Percent"),
                            ("AMOUNT", "Amount"),
                            ("FREE", "Free (100%)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                (
                    "scope",
                    models.CharField(
                        choices=[("ORDER", "Order"), ("ITEM", "Item")],
                        default="ORDER",
                        max_length=8,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pos.discountreason",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("PAID", "Paid"), ("VOID", "Void")],
                        default="OPEN",
                        max_length=8,
                    ),
                ),
                (
                    "order_discount_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PERCENT", "Percent"),
                            ("AMOUNT", "Amount"),
                            ("FREE", "Free (100%)"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "order_discount_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("discount_total", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("tax_total", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("grand_total", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_sales_closed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_sales_opened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_discount_reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pos.discountreason",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("CASH", "Cash"), ("CARD", "Card"), ("OTHER", "Other")],
                        default="CASH",
                        max_length=8,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "received_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="pos.sale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title_snapshot", models.CharField(max_length=160)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PERCENT", "Percent"),
                            ("AMOUNT", "Amount"),
                            ("FREE", "Free (100%)"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("discount_value", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("tax_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("line_subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("line_discount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("line_total", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "menu_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="menu.itemvariant"
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pos.sale",
                    ),
                ),
            ],
        ),
    ]
