# Generated by Django 5.2.8 on 2025-11-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='order_discount_type',
            field=models.CharField(blank=True, choices=[('PERCENT', 'Percent'), ('AMOUNT', 'Amount'), ('FREE', 'Free (100%)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('PERCENT', 'Percent'), ('AMOUNT', 'Amount'), ('FREE', 'Free (100%)')], max_length=10),
        ),
    ]
