# Generated by Django 5.2.8 on 2026-01-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newspost_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='body_de',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='body_es',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='body_fr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='slug_de',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='slug_es',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='slug_fr',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
