# Generated by Django 5.2.8 on 2025-11-18 15:34

import app.core.encryption
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BadgeDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "emoji",
                    models.CharField(
                        blank=True, help_text="Optional short emoji label (e.g. '🍺')", max_length=8
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FieldPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="e.g. 'phone', 'address', 'birth_date', 'email', 'role_title'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("ADMIN_ONLY", "Admins only"),
                            ("STAFF_ONLY", "Staff users"),
                            ("AUTHENTICATED", "All logged-in users"),
                            ("PUBLIC", "Public/Anyone"),
                        ],
                        default="AUTHENTICATED",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "field policies",
            },
        ),
        migrations.CreateModel(
            name="GroupMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(default=1000, help_text="Lower = higher priority"),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "ordering": ["rank", "group__name"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("legal_name", app.core.encryption.EncryptedCharField(blank=True)),
                ("chosen_name", app.core.encryption.EncryptedCharField(blank=True)),
                (
                    "pronouns",
                    app.core.encryption.EncryptedCharField(
                        blank=True, help_text="e.g. she/her, he/him, they/them"
                    ),
                ),
                ("birth_date", app.core.encryption.EncryptedDateField(blank=True, null=True)),
                ("email", app.core.encryption.EncryptedEmailField(blank=True)),
                ("phone", app.core.encryption.EncryptedCharField(blank=True)),
                ("address", app.core.encryption.EncryptedTextField(blank=True)),
                (
                    "role_title",
                    app.core.encryption.EncryptedCharField(
                        blank=True, help_text="Free-text role label, e.g. 'Bar lead'"
                    ),
                ),
                ("duties", app.core.encryption.EncryptedTextField(blank=True)),
                ("force_password_change", models.BooleanField(default=True)),
                ("has_selected_visibility", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("badges", models.ManyToManyField(blank=True, to="users.badgedefinition")),
                (
                    "primary_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_members",
                        to="auth.group",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
                "permissions": (("can_impersonate", "Can impersonate other users"),),
            },
        ),
    ]
