# Generated by Django 5.2.8 on 2025-11-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('menu', '0003_category_kind_generic'),
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='menu_items',
            field=models.ManyToManyField(blank=True, help_text='Reference only.', related_name='inventory_links', to='menu.item'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='merch_products',
            field=models.ManyToManyField(blank=True, help_text='Reference only.', related_name='inventory_links', to='merch.product'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit_label',
            field=models.CharField(blank=True, default='', help_text='Fallback label if a formal unit is not available.', max_length=32),
        ),
    ]
