# Generated by Django 5.2.8 on 2025-11-26 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_menu_items_and_more'),
        ('inventory', '0002_inventorypackage'),
    ]

    operations = [
    ]
