# Generated by Django 5.2.8 on 2025-11-18 15:34

import app.merch.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("name_en", models.CharField(max_length=160, null=True)),
                ("name_es", models.CharField(max_length=160, null=True)),
                ("name_de", models.CharField(max_length=160, null=True)),
                ("name_fr", models.CharField(max_length=160, null=True)),
                ("slug", models.SlugField(blank=True, max_length=180)),
                ("slug_en", models.SlugField(blank=True, max_length=180, null=True)),
                ("slug_es", models.SlugField(blank=True, max_length=180, null=True)),
                ("slug_de", models.SlugField(blank=True, max_length=180, null=True)),
                ("slug_fr", models.SlugField(blank=True, max_length=180, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="merch.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_en", models.CharField(max_length=200, null=True)),
                ("name_es", models.CharField(max_length=200, null=True)),
                ("name_de", models.CharField(max_length=200, null=True)),
                ("name_fr", models.CharField(max_length=200, null=True)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                ("slug_en", models.SlugField(blank=True, max_length=220, null=True)),
                ("slug_es", models.SlugField(blank=True, max_length=220, null=True)),
                ("slug_de", models.SlugField(blank=True, max_length=220, null=True)),
                ("slug_fr", models.SlugField(blank=True, max_length=220, null=True)),
                ("description", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_es", models.TextField(blank=True, null=True)),
                ("description_de", models.TextField(blank=True, null=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                ("visible_public", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
                (
                    "base_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional. If omitted, the min variant price is shown.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="merch.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-featured", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to=app.merch.models.product_image_upload_path)),
                ("alt_text", models.CharField(blank=True, max_length=160)),
                ("alt_text_en", models.CharField(blank=True, max_length=160, null=True)),
                ("alt_text_es", models.CharField(blank=True, max_length=160, null=True)),
                ("alt_text_de", models.CharField(blank=True, max_length=160, null=True)),
                ("alt_text_fr", models.CharField(blank=True, max_length=160, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="merch.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("product",),
                        name="unique_primary_image_per_product",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "size_label",
                    models.CharField(
                        blank=True,
                        help_text="Clothing size (e.g., S, M, L) or free text",
                        max_length=32,
                    ),
                ),
                (
                    "size_label_en",
                    models.CharField(
                        blank=True,
                        help_text="Clothing size (e.g., S, M, L) or free text",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "size_label_es",
                    models.CharField(
                        blank=True,
                        help_text="Clothing size (e.g., S, M, L) or free text",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "size_label_de",
                    models.CharField(
                        blank=True,
                        help_text="Clothing size (e.g., S, M, L) or free text",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "size_label_fr",
                    models.CharField(
                        blank=True,
                        help_text="Clothing size (e.g., S, M, L) or free text",
                        max_length=32,
                        null=True,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=40)),
                ("color_en", models.CharField(blank=True, max_length=40, null=True)),
                ("color_es", models.CharField(blank=True, max_length=40, null=True)),
                ("color_de", models.CharField(blank=True, max_length=40, null=True)),
                ("color_fr", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "length_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "width_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=64)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "stock",
                    models.IntegerField(
                        default=0, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="merch.product",
                    ),
                ),
            ],
            options={
                "ordering": ["price", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("sku", ""), _negated=True),
                        fields=("product", "sku"),
                        name="unique_sku_per_product_when_set",
                    )
                ],
            },
        ),
    ]
