# Generated by Django 5.2.8 on 2025-11-18 15:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="If flagged, suggest this preset during event creation.",
                    ),
                ),
                (
                    "visibility_key",
                    models.CharField(
                        blank=True,
                        help_text="Visibility rule key controlling who can use this preset.",
                        max_length=120,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShiftTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "start_reference",
                    models.CharField(
                        choices=[("event_start", "Event start"), ("doors", "Doors open")],
                        default="doors",
                        help_text="Base time used to calculate the shift start.",
                        max_length=20,
                    ),
                ),
                (
                    "start_offset_minutes",
                    models.IntegerField(
                        default=0,
                        help_text="Minutes relative to the chosen reference (negative = before).",
                    ),
                ),
                (
                    "end_offset_minutes",
                    models.IntegerField(
                        default=0,
                        help_text="Minutes to subtract from the closing time (positive = earlier).",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Optional fixed duration per segment (0 = auto evenly split).",
                    ),
                ),
                (
                    "segment_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many sequential segments to split the coverage into.",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of people required in each segment.",
                        verbose_name="People per segment",
                    ),
                ),
                ("allow_signup", models.BooleanField(default=True)),
                ("visibility_key", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ShiftPresetSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "start_offset_minutes",
                    models.IntegerField(
                        default=0, help_text="Minutes relative to event start (negative = before)."
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(default=120, help_text="Length in minutes."),
                ),
                ("capacity", models.PositiveIntegerField(default=1)),
                (
                    "allow_signup",
                    models.BooleanField(
                        default=True, help_text="If false, shift can only be assigned manually."
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "preset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="shifts.shiftpreset",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("template_segment", models.PositiveSmallIntegerField(default=1)),
                ("template_staff_position", models.PositiveSmallIntegerField(default=1)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("capacity", models.PositiveIntegerField(default=1)),
                ("allow_signup", models.BooleanField(default=True)),
                ("visibility_key", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed"), ("archived", "Archived")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shifts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="events.event",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shifts_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preset_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_shifts",
                        to="shifts.shiftpresetslot",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_shifts",
                        to="shifts.shifttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["start_at", "title"],
                "unique_together": {
                    ("event", "template", "template_segment", "template_staff_position", "start_at")
                },
            },
        ),
        migrations.CreateModel(
            name="ShiftAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("assigned", "Assigned"),
                            ("completed", "Completed"),
                            ("dropped", "Released"),
                        ],
                        default="requested",
                        max_length=12,
                    ),
                ),
                ("assigned_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shift_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="shifts.shift",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
                "unique_together": {("shift", "user")},
            },
        ),
    ]
