# Generated by Django 5.2.8 on 2025-11-18 15:34

import app.core.encryption
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("VENUE", "Venue / Club"),
                            ("BAND", "Band / Artist"),
                            ("PERSON", "Person / Blog"),
                        ],
                        default="VENUE",
                        max_length=10,
                    ),
                ),
                ("org_name", app.core.encryption.EncryptedCharField(blank=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("address_street", app.core.encryption.EncryptedCharField(blank=True)),
                ("address_number", app.core.encryption.EncryptedCharField(blank=True)),
                ("address_postal_code", app.core.encryption.EncryptedCharField(blank=True)),
                ("address_city", app.core.encryption.EncryptedCharField(blank=True)),
                ("address_country", app.core.encryption.EncryptedCharField(blank=True)),
                (
                    "address_autocomplete",
                    models.BooleanField(
                        default=False,
                        help_text="Enable address autocomplete (requires JS integration).",
                    ),
                ),
                ("contact_email", app.core.encryption.EncryptedEmailField(blank=True)),
                ("contact_phone", app.core.encryption.EncryptedCharField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                ("social_facebook", models.URLField(blank=True)),
                ("social_instagram", models.URLField(blank=True)),
                ("social_twitter", models.URLField(blank=True, help_text="X / Twitter URL")),
                ("social_tiktok", models.URLField(blank=True)),
                ("social_youtube", models.URLField(blank=True)),
                ("social_spotify", models.URLField(blank=True)),
                ("social_soundcloud", models.URLField(blank=True)),
                ("social_bandcamp", models.URLField(blank=True)),
                ("social_linkedin", models.URLField(blank=True)),
                ("social_mastodon", models.URLField(blank=True)),
                (
                    "same_as",
                    app.core.encryption.EncryptedTextField(
                        blank=True, help_text="schema.org sameAs: one URL per line"
                    ),
                ),
                (
                    "geo_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, help_text="Latitude", max_digits=9, null=True
                    ),
                ),
                (
                    "geo_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, help_text="Longitude", max_digits=9, null=True
                    ),
                ),
                (
                    "price_range",
                    models.CharField(blank=True, help_text="e.g., $, $$, $$$", max_length=20),
                ),
                (
                    "default_currency",
                    models.CharField(
                        default="EUR",
                        help_text="Currency code (suggested list + free text)",
                        max_length=8,
                    ),
                ),
                ("membership_enabled", models.BooleanField(default=False)),
                (
                    "membership_hint",
                    models.CharField(
                        blank=True,
                        help_text="Short label shown next to money icon.",
                        max_length=200,
                    ),
                ),
                (
                    "public_pages_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Expose the public-facing site powered by the Pages app.",
                    ),
                ),
                (
                    "enabled_languages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of enabled language codes (e.g., ['en', 'es', 'de']). Leave empty to enable all languages.",
                    ),
                ),
                (
                    "required_pages",
                    models.TextField(
                        blank=True,
                        help_text="Legacy field for auto-created pages; no longer used by the UI.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("smoking_allowed", models.BooleanField(blank=True, null=True)),
                ("pets_allowed_text", models.CharField(blank=True, max_length=120)),
                ("typical_age_range", models.CharField(blank=True, max_length=20)),
                ("acc_step_free", models.BooleanField(default=False)),
                ("acc_wheelchair", models.BooleanField(default=False)),
                ("acc_accessible_wc", models.BooleanField(default=False)),
                ("acc_visual_aid", models.BooleanField(default=False)),
                ("acc_service_animals", models.BooleanField(default=False)),
                ("accessibility_summary", models.TextField(blank=True)),
                ("lgbtq_friendly", models.BooleanField(default=False)),
                ("minors_policy_note", models.CharField(blank=True, max_length=200)),
                ("maximum_attendee_capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("awareness_team_available", models.BooleanField(default=False)),
                (
                    "awareness_contact",
                    app.core.encryption.EncryptedCharField(
                        blank=True,
                        help_text="Phone, email, URL, or a short instruction (free text).",
                    ),
                ),
                (
                    "publish_opening_times",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, opening times will be rendered on public pages.",
                        verbose_name="Show opening times on public pages",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisibilityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        max_length=120,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[\\w\\.\\-:]+$",
                                "Key may contain letters, numbers, underscores, hyphens, dots, or colons.",
                            )
                        ],
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="Human-friendly name; editable.", max_length=200
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("allowed_groups", models.ManyToManyField(blank=True, to="auth.group")),
            ],
        ),
        migrations.CreateModel(
            name="OpeningHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Mon"),
                            (1, "Tue"),
                            (2, "Wed"),
                            (3, "Thu"),
                            (4, "Fri"),
                            (5, "Sat"),
                            (6, "Sun"),
                        ],
                        default=0,
                    ),
                ),
                ("closed", models.BooleanField(default=False)),
                ("open_time", models.TimeField(blank=True, null=True)),
                ("close_time", models.TimeField(blank=True, null=True)),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hours",
                        to="setup.sitesettings",
                    ),
                ),
            ],
            options={
                "unique_together": {("settings", "weekday")},
            },
        ),
        migrations.CreateModel(
            name="MembershipTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("months", models.PositiveIntegerField(default=12)),
                (
                    "price_minor",
                    models.PositiveIntegerField(
                        default=0, help_text="In minor units (e.g. cents/rappen)"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="setup.sitesettings",
                    ),
                ),
            ],
            options={
                "unique_together": {("settings", "name")},
            },
        ),
    ]
