# Generated by Django 5.2.8 on 2025-11-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setup", "0004_inventory_alert_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="dev_login_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Show the developer login shortcut when running in development/test.",
            ),
        ),
    ]

