# Generated by Django 5.2.8 on 2025-11-18 15:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=16, unique=True)),
                ("display", models.CharField(max_length=32)),
                ("display_en", models.CharField(max_length=32, null=True)),
                ("display_es", models.CharField(max_length=32, null=True)),
                ("display_de", models.CharField(max_length=32, null=True)),
                ("display_fr", models.CharField(max_length=32, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("volume", "Volume"), ("mass", "Mass"), ("count", "Count")],
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "code"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("name_en", models.CharField(max_length=120, null=True)),
                ("name_es", models.CharField(max_length=120, null=True)),
                ("name_de", models.CharField(max_length=120, null=True)),
                ("name_fr", models.CharField(max_length=120, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=140,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid “slug” (letters, numbers, underscores, or hyphens).",
                                regex="^[a-zA-Z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "slug_en",
                    models.SlugField(
                        blank=True,
                        max_length=140,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid “slug” (letters, numbers, underscores, or hyphens).",
                                regex="^[a-zA-Z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "slug_es",
                    models.SlugField(
                        blank=True,
                        max_length=140,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid “slug” (letters, numbers, underscores, or hyphens).",
                                regex="^[a-zA-Z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "slug_de",
                    models.SlugField(
                        blank=True,
                        max_length=140,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid “slug” (letters, numbers, underscores, or hyphens).",
                                regex="^[a-zA-Z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "slug_fr",
                    models.SlugField(
                        blank=True,
                        max_length=140,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid “slug” (letters, numbers, underscores, or hyphens).",
                                regex="^[a-zA-Z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "kind",
                    models.CharField(choices=[("drink", "Drink"), ("food", "Food")], max_length=16),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="menu.category",
                    ),
                ),
            ],
            options={
                "ordering": ["parent__id", "name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("name_en", models.CharField(max_length=160, null=True)),
                ("name_es", models.CharField(max_length=160, null=True)),
                ("name_de", models.CharField(max_length=160, null=True)),
                ("name_fr", models.CharField(max_length=160, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=180,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid “slug” (letters, numbers, underscores, or hyphens).",
                                regex="^[a-zA-Z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "slug_en",
                    models.SlugField(
                        blank=True,
                        max_length=180,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid “slug” (letters, numbers, underscores, or hyphens).",
                                regex="^[a-zA-Z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "slug_es",
                    models.SlugField(
                        blank=True,
                        max_length=180,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid “slug” (letters, numbers, underscores, or hyphens).",
                                regex="^[a-zA-Z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "slug_de",
                    models.SlugField(
                        blank=True,
                        max_length=180,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid “slug” (letters, numbers, underscores, or hyphens).",
                                regex="^[a-zA-Z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "slug_fr",
                    models.SlugField(
                        blank=True,
                        max_length=180,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid “slug” (letters, numbers, underscores, or hyphens).",
                                regex="^[a-zA-Z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_es", models.TextField(blank=True, null=True)),
                ("description_de", models.TextField(blank=True, null=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                ("allergens_note", models.CharField(blank=True, max_length=240)),
                ("allergens_note_en", models.CharField(blank=True, max_length=240, null=True)),
                ("allergens_note_es", models.CharField(blank=True, max_length=240, null=True)),
                ("allergens_note_de", models.CharField(blank=True, max_length=240, null=True)),
                ("allergens_note_fr", models.CharField(blank=True, max_length=240, null=True)),
                ("vegan", models.BooleanField(default=False)),
                ("vegetarian", models.BooleanField(default=False)),
                ("gluten_free", models.BooleanField(default=False)),
                ("sugar_free", models.BooleanField(default=False)),
                ("lactose_free", models.BooleanField(default=False)),
                ("nut_free", models.BooleanField(default=False)),
                ("halal", models.BooleanField(default=False)),
                ("kosher", models.BooleanField(default=False)),
                ("visible_public", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
                ("sold_out_until", models.DateTimeField(blank=True, null=True)),
                ("new_until", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="menu.category",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ItemVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=64)),
                ("label_en", models.CharField(blank=True, max_length=64, null=True)),
                ("label_es", models.CharField(blank=True, max_length=64, null=True)),
                ("label_de", models.CharField(blank=True, max_length=64, null=True)),
                ("label_fr", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "abv",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Alcohol by volume (%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="menu.item",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="menu.unit"),
                ),
            ],
            options={
                "ordering": ["item__name", "unit__kind", "quantity", "label"],
            },
        ),
        migrations.CreateModel(
            name="UnitGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("name_en", models.CharField(max_length=64, null=True)),
                ("name_es", models.CharField(max_length=64, null=True)),
                ("name_de", models.CharField(max_length=64, null=True)),
                ("name_fr", models.CharField(max_length=64, null=True)),
                ("allowed_units", models.ManyToManyField(blank=True, to="menu.unit")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="unit_group_override",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="menu.unitgroup",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="unit_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="menu.unitgroup",
            ),
        ),
    ]
