# Generated by Django 5.2.8 on 2025-11-18 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, default="", max_length=100)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("storage_path", models.CharField(blank=True, default="", max_length=500)),
                ("sha256", models.CharField(blank=True, default="", max_length=64)),
                ("is_inline", models.BooleanField(default=False)),
                ("content_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("clean", "Clean"),
                            ("blocked", "Blocked"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("scan_detail", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="AudienceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source", models.CharField(default="manual", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=500)),
                ("body_text", models.TextField(blank=True, default="")),
                ("body_html", models.TextField(blank=True, default="")),
                ("to_json", models.JSONField(blank=True, default=list, null=True)),
                ("cc_json", models.JSONField(blank=True, default=list, null=True)),
                ("bcc_json", models.JSONField(blank=True, default=list, null=True)),
                ("attachments_meta", models.JSONField(blank=True, default=list, null=True)),
                ("autosaved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("editing", "Editing"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("discarded", "Discarded"),
                        ],
                        default="editing",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="InternalTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField()),
                ("is_system", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                ("from_name", models.CharField(blank=True, default="", max_length=120)),
                ("from_address", models.EmailField(blank=True, default="", max_length=254)),
                ("signature_html", models.TextField(blank=True, default="")),
                ("signature_text", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("inbound", "Inbound"),
                            ("outbound", "Outbound"),
                            ("internal", "Internal"),
                        ],
                        default="internal",
                        max_length=10,
                    ),
                ),
                ("sender_display", models.CharField(blank=True, default="", max_length=200)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("message_id", models.CharField(blank=True, default="", max_length=512)),
                ("in_reply_to", models.CharField(blank=True, default="", max_length=512)),
                ("references", models.TextField(blank=True, default="")),
                ("headers", models.JSONField(blank=True, null=True)),
                ("body_text", models.TextField(blank=True, default="")),
                ("body_html_sanitized", models.TextField(blank=True, default="")),
                ("has_trackers", models.BooleanField(default=False)),
                ("size_bytes", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("internal", "Internal"), ("email", "Email")],
                        default="internal",
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity_at", models.DateTimeField(auto_now=True)),
                ("has_attachments", models.BooleanField(default=False)),
                ("is_closed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-last_activity_at"],
            },
        ),
        migrations.CreateModel(
            name="ReadReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("read_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="UserThreadState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                ("starred", models.BooleanField(default=False)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
