# Generated by Django 5.2.8 on 2025-11-18 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("comms", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="audiencelink",
            name="badge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.badgedefinition",
            ),
        ),
        migrations.AddField(
            model_name="audiencelink",
            name="group",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="audiencelink",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="draft",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comms_drafts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="internaltarget",
            name="badge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.badgedefinition",
            ),
        ),
        migrations.AddField(
            model_name="internaltarget",
            name="group",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="internaltarget",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="comms.mailaccount",
            ),
        ),
        migrations.AddField(
            model_name="draft",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="comms.mailaccount",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="comms.mailaccount",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="comms.message",
            ),
        ),
        migrations.AddField(
            model_name="messagethread",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="comms.mailaccount",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="comms.messagethread",
            ),
        ),
        migrations.AddField(
            model_name="internaltarget",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="internal_targets",
                to="comms.messagethread",
            ),
        ),
        migrations.AddField(
            model_name="draft",
            name="thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="comms.messagethread",
            ),
        ),
        migrations.AddField(
            model_name="audiencelink",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audiences",
                to="comms.messagethread",
            ),
        ),
        migrations.AddField(
            model_name="readreceipt",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="read_receipts",
                to="comms.message",
            ),
        ),
        migrations.AddField(
            model_name="readreceipt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comms_reads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userthreadstate",
            name="labels",
            field=models.ManyToManyField(blank=True, to="comms.label"),
        ),
        migrations.AddField(
            model_name="userthreadstate",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_states",
                to="comms.messagethread",
            ),
        ),
        migrations.AddField(
            model_name="userthreadstate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thread_states",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="label",
            unique_together={("account", "slug")},
        ),
        migrations.AddConstraint(
            model_name="messagethread",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("account__isnull", False), ("type", "email")),
                    models.Q(("account__isnull", True), ("type", "internal")),
                    _connector="OR",
                ),
                name="comms_thread_type_account_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("account__isnull", True), ("direction", "internal")),
                    ("direction__in", ["inbound", "outbound"]),
                    _connector="OR",
                ),
                name="comms_message_direction_account_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="internaltarget",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("badge__isnull", False), ("group__isnull", True), ("user__isnull", True)
                    ),
                    models.Q(
                        ("badge__isnull", True), ("group__isnull", False), ("user__isnull", True)
                    ),
                    models.Q(
                        ("badge__isnull", True), ("group__isnull", True), ("user__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="comms_internal_target_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="internaltarget",
            constraint=models.UniqueConstraint(
                fields=("thread", "badge", "group", "user"),
                name="comms_internal_target_unique_member",
            ),
        ),
        migrations.AddConstraint(
            model_name="audiencelink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("badge__isnull", False), ("group__isnull", True), ("user__isnull", True)
                    ),
                    models.Q(
                        ("badge__isnull", True), ("group__isnull", False), ("user__isnull", True)
                    ),
                    models.Q(
                        ("badge__isnull", True), ("group__isnull", True), ("user__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="comms_audience_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="audiencelink",
            constraint=models.UniqueConstraint(
                fields=("thread", "badge", "group", "user"), name="comms_audience_unique_member"
            ),
        ),
        migrations.AddIndex(
            model_name="readreceipt",
            index=models.Index(fields=["user", "-read_at"], name="comms_readr_user_id_b31cc9_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="readreceipt",
            unique_together={("message", "user")},
        ),
        migrations.AddIndex(
            model_name="userthreadstate",
            index=models.Index(
                fields=["user", "archived", "-last_read_at"], name="comms_usert_user_id_e226f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userthreadstate",
            index=models.Index(
                fields=["user", "starred", "-last_read_at"], name="comms_usert_user_id_3528da_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userthreadstate",
            unique_together={("thread", "user")},
        ),
    ]
