# Generated by Django 5.2.8 on 2025-11-18 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("name_en", models.CharField(max_length=120, null=True)),
                ("name_es", models.CharField(max_length=120, null=True)),
                ("name_de", models.CharField(max_length=120, null=True)),
                ("name_fr", models.CharField(max_length=120, null=True)),
                ("slug", models.SlugField(max_length=140)),
                ("slug_en", models.SlugField(max_length=140, null=True)),
                ("slug_es", models.SlugField(max_length=140, null=True)),
                ("slug_de", models.SlugField(max_length=140, null=True)),
                ("slug_fr", models.SlugField(max_length=140, null=True)),
                ("description", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_es", models.TextField(blank=True, null=True)),
                ("description_de", models.TextField(blank=True, null=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Optional hex color (without #) used for UI accents.",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EventPerformer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Shown publicly; defaults to the linked band's name.",
                        max_length=200,
                    ),
                ),
                (
                    "display_name_en",
                    models.CharField(
                        blank=True,
                        help_text="Shown publicly; defaults to the linked band's name.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "display_name_es",
                    models.CharField(
                        blank=True,
                        help_text="Shown publicly; defaults to the linked band's name.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "display_name_de",
                    models.CharField(
                        blank=True,
                        help_text="Shown publicly; defaults to the linked band's name.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "display_name_fr",
                    models.CharField(
                        blank=True,
                        help_text="Shown publicly; defaults to the linked band's name.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "performer_type",
                    models.CharField(
                        blank=True,
                        help_text="Optional override (DJ set, acoustic, support, etc.).",
                        max_length=16,
                    ),
                ),
                (
                    "performer_type_en",
                    models.CharField(
                        blank=True,
                        help_text="Optional override (DJ set, acoustic, support, etc.).",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "performer_type_es",
                    models.CharField(
                        blank=True,
                        help_text="Optional override (DJ set, acoustic, support, etc.).",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "performer_type_de",
                    models.CharField(
                        blank=True,
                        help_text="Optional override (DJ set, acoustic, support, etc.).",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "performer_type_fr",
                    models.CharField(
                        blank=True,
                        help_text="Optional override (DJ set, acoustic, support, etc.).",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("slot_starts_at", models.DateTimeField(blank=True, null=True)),
                ("slot_ends_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("notes_en", models.TextField(blank=True, null=True)),
                ("notes_es", models.TextField(blank=True, null=True)),
                ("notes_de", models.TextField(blank=True, null=True)),
                ("notes_fr", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["order", "slot_starts_at", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="EventRecurrenceException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("occurrence_start", models.DateTimeField()),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("skip", "Skip occurrence"),
                            ("override", "Override occurrence"),
                            ("holiday", "Holiday blackout"),
                        ],
                        default="skip",
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-occurrence_start"],
            },
        ),
        migrations.CreateModel(
            name="HolidayWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("name_en", models.CharField(max_length=140, null=True)),
                ("name_es", models.CharField(max_length=140, null=True)),
                ("name_de", models.CharField(max_length=140, null=True)),
                ("name_fr", models.CharField(max_length=140, null=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "applies_to_internal",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, internal events will still be scheduled.",
                    ),
                ),
                (
                    "applies_to_public",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, public events will still be scheduled.",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=240)),
                ("note_en", models.CharField(blank=True, max_length=240, null=True)),
                ("note_es", models.CharField(blank=True, max_length=240, null=True)),
                ("note_de", models.CharField(blank=True, max_length=240, null=True)),
                ("note_fr", models.CharField(blank=True, max_length=240, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_es", models.CharField(max_length=200, null=True)),
                ("title_de", models.CharField(max_length=200, null=True)),
                ("title_fr", models.CharField(max_length=200, null=True)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                ("slug_en", models.SlugField(blank=True, max_length=220, null=True)),
                ("slug_es", models.SlugField(blank=True, max_length=220, null=True)),
                ("slug_de", models.SlugField(blank=True, max_length=220, null=True)),
                ("slug_fr", models.SlugField(blank=True, max_length=220, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("public", "Public"), ("internal", "Internal")],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("hero_image", models.ImageField(blank=True, null=True, upload_to="events/hero/")),
                (
                    "teaser",
                    models.CharField(
                        blank=True,
                        help_text="Short summary for cards, social previews, SEO descriptions.",
                        max_length=280,
                    ),
                ),
                (
                    "teaser_en",
                    models.CharField(
                        blank=True,
                        help_text="Short summary for cards, social previews, SEO descriptions.",
                        max_length=280,
                        null=True,
                    ),
                ),
                (
                    "teaser_es",
                    models.CharField(
                        blank=True,
                        help_text="Short summary for cards, social previews, SEO descriptions.",
                        max_length=280,
                        null=True,
                    ),
                ),
                (
                    "teaser_de",
                    models.CharField(
                        blank=True,
                        help_text="Short summary for cards, social previews, SEO descriptions.",
                        max_length=280,
                        null=True,
                    ),
                ),
                (
                    "teaser_fr",
                    models.CharField(
                        blank=True,
                        help_text="Short summary for cards, social previews, SEO descriptions.",
                        max_length=280,
                        null=True,
                    ),
                ),
                (
                    "description_public",
                    models.TextField(
                        blank=True, help_text="Markdown or HTML rendered on the public site."
                    ),
                ),
                (
                    "description_public_en",
                    models.TextField(
                        blank=True,
                        help_text="Markdown or HTML rendered on the public site.",
                        null=True,
                    ),
                ),
                (
                    "description_public_es",
                    models.TextField(
                        blank=True,
                        help_text="Markdown or HTML rendered on the public site.",
                        null=True,
                    ),
                ),
                (
                    "description_public_de",
                    models.TextField(
                        blank=True,
                        help_text="Markdown or HTML rendered on the public site.",
                        null=True,
                    ),
                ),
                (
                    "description_public_fr",
                    models.TextField(
                        blank=True,
                        help_text="Markdown or HTML rendered on the public site.",
                        null=True,
                    ),
                ),
                (
                    "description_internal",
                    models.TextField(
                        blank=True,
                        help_text="Staff-only notes (door team briefings, settlement notes, etc.)",
                    ),
                ),
                (
                    "description_internal_en",
                    models.TextField(
                        blank=True,
                        help_text="Staff-only notes (door team briefings, settlement notes, etc.)",
                        null=True,
                    ),
                ),
                (
                    "description_internal_es",
                    models.TextField(
                        blank=True,
                        help_text="Staff-only notes (door team briefings, settlement notes, etc.)",
                        null=True,
                    ),
                ),
                (
                    "description_internal_de",
                    models.TextField(
                        blank=True,
                        help_text="Staff-only notes (door team briefings, settlement notes, etc.)",
                        null=True,
                    ),
                ),
                (
                    "description_internal_fr",
                    models.TextField(
                        blank=True,
                        help_text="Staff-only notes (door team briefings, settlement notes, etc.)",
                        null=True,
                    ),
                ),
                ("doors_at", models.DateTimeField(blank=True, null=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("curfew_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recurrence_frequency",
                    models.CharField(
                        choices=[
                            ("none", "Does not repeat"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Every other week"),
                            ("monthly_date", "Monthly (specific date)"),
                            ("monthly_weekday", "Monthly (weekday, e.g. 1st Thursday)"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                (
                    "recurrence_parent_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Original start datetime for the overridden occurrence.",
                        null=True,
                    ),
                ),
                (
                    "recurrence_weekday",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Weekday used for recurring patterns.",
                        null=True,
                    ),
                ),
                (
                    "recurrence_week_of_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "First"),
                            (2, "Second"),
                            (3, "Third"),
                            (4, "Fourth"),
                            (5, "Fifth"),
                        ],
                        help_text="Which week (1st, 2nd, etc.) of the month for weekday-based recurrences.",
                        null=True,
                    ),
                ),
                (
                    "recurrence_day_of_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Specific day of the month (1-31) for date-based recurrences.",
                        null=True,
                    ),
                ),
                (
                    "recurrence_next_start_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional next scheduled start when managing recurring series.",
                        null=True,
                    ),
                ),
                ("ticket_url", models.URLField(blank=True)),
                (
                    "ticket_price_from",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
                ),
                (
                    "ticket_price_to",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
                ),
                ("is_free", models.BooleanField(default=False)),
                (
                    "requires_shifts",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, event will appear in the shift planner.",
                    ),
                ),
                ("venue_name", models.CharField(blank=True, max_length=200)),
                ("venue_name_en", models.CharField(blank=True, max_length=200, null=True)),
                ("venue_name_es", models.CharField(blank=True, max_length=200, null=True)),
                ("venue_name_de", models.CharField(blank=True, max_length=200, null=True)),
                ("venue_name_fr", models.CharField(blank=True, max_length=200, null=True)),
                ("venue_address", models.CharField(blank=True, max_length=255)),
                ("venue_postal_code", models.CharField(blank=True, max_length=32)),
                ("venue_city", models.CharField(blank=True, max_length=120)),
                ("venue_country", models.CharField(blank=True, max_length=120)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_title_en", models.CharField(blank=True, max_length=70, null=True)),
                ("seo_title_es", models.CharField(blank=True, max_length=70, null=True)),
                ("seo_title_de", models.CharField(blank=True, max_length=70, null=True)),
                ("seo_title_fr", models.CharField(blank=True, max_length=70, null=True)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                ("seo_description_en", models.CharField(blank=True, max_length=160, null=True)),
                ("seo_description_es", models.CharField(blank=True, max_length=160, null=True)),
                ("seo_description_de", models.CharField(blank=True, max_length=160, null=True)),
                ("seo_description_fr", models.CharField(blank=True, max_length=160, null=True)),
                (
                    "visibility_key",
                    models.CharField(
                        blank=True,
                        help_text="Visibility rule key (managed via the setup visibility cogs).",
                        max_length=120,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recurrence_parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, this event overrides a single occurrence of the parent recurrence.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence_overrides",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-starts_at", "title"],
            },
        ),
    ]
