# Generated by Django 5.2.8 on 2025-11-18 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bands", "0001_initial"),
        ("events", "0001_initial"),
        ("shifts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="standard_shifts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select standard shifts (door, bar, etc.) to generate for this event.",
                related_name="events",
                to="shifts.shifttemplate",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Pick all that apply (used for filtering and SEO markup).",
                related_name="events",
                to="events.eventcategory",
            ),
        ),
        migrations.AddField(
            model_name="eventperformer",
            name="band",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_slots",
                to="bands.band",
            ),
        ),
        migrations.AddField(
            model_name="eventperformer",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performers",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="eventrecurrenceexception",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurrence_exceptions",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="eventrecurrenceexception",
            name="override_event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurrence_exception",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="holidaywindow",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="holiday_windows_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="holidaywindow",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="holiday_windows_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="eventrecurrenceexception",
            constraint=models.UniqueConstraint(
                fields=("event", "occurrence_start"), name="unique_event_occurrence_exception"
            ),
        ),
    ]
