# Generated by Django 5.2.8 on 2025-11-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='name_de',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='name_en',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='name_es',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='name_fr',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
    ]
