# Generated by Django 5.2.8 on 2025-11-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Band",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "performer_type",
                    models.CharField(
                        choices=[("band", "Band"), ("dj", "DJ"), ("solo", "Solo artist")],
                        default="band",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("name_en", models.CharField(max_length=200, null=True)),
                ("name_es", models.CharField(max_length=200, null=True)),
                ("name_de", models.CharField(max_length=200, null=True)),
                ("name_fr", models.CharField(max_length=200, null=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Auto-filled from name; you can edit.", max_length=220
                    ),
                ),
                (
                    "slug_en",
                    models.SlugField(
                        help_text="Auto-filled from name; you can edit.", max_length=220, null=True
                    ),
                ),
                (
                    "slug_es",
                    models.SlugField(
                        help_text="Auto-filled from name; you can edit.", max_length=220, null=True
                    ),
                ),
                (
                    "slug_de",
                    models.SlugField(
                        help_text="Auto-filled from name; you can edit.", max_length=220, null=True
                    ),
                ),
                (
                    "slug_fr",
                    models.SlugField(
                        help_text="Auto-filled from name; you can edit.", max_length=220, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_es", models.TextField(blank=True, null=True)),
                ("description_de", models.TextField(blank=True, null=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="bands/")),
                (
                    "contact_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("url", "Website/Link"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "contact_value",
                    models.CharField(
                        blank=True, help_text="Email, phone number, or URL.", max_length=255
                    ),
                ),
                (
                    "contact_notes",
                    models.CharField(
                        blank=True, help_text="How contact was made / extra notes.", max_length=255
                    ),
                ),
                (
                    "contact_notes_en",
                    models.CharField(
                        blank=True,
                        help_text="How contact was made / extra notes.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "contact_notes_es",
                    models.CharField(
                        blank=True,
                        help_text="How contact was made / extra notes.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "contact_notes_de",
                    models.CharField(
                        blank=True,
                        help_text="How contact was made / extra notes.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "contact_notes_fr",
                    models.CharField(
                        blank=True,
                        help_text="How contact was made / extra notes.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "compensation_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed fee"),
                            ("door", "Door deal"),
                            ("unpaid", "Unpaid / promo"),
                        ],
                        default="unpaid",
                        max_length=10,
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Paid amount for fixed fee.",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "entry_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Entry price if door deal.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "payout_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Payout amount they got.",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "comment_internal",
                    models.TextField(blank=True, help_text="Private notes for staff (not public)."),
                ),
                (
                    "comment_internal_en",
                    models.TextField(
                        blank=True, help_text="Private notes for staff (not public).", null=True
                    ),
                ),
                (
                    "comment_internal_es",
                    models.TextField(
                        blank=True, help_text="Private notes for staff (not public).", null=True
                    ),
                ),
                (
                    "comment_internal_de",
                    models.TextField(
                        blank=True, help_text="Private notes for staff (not public).", null=True
                    ),
                ),
                (
                    "comment_internal_fr",
                    models.TextField(
                        blank=True, help_text="Private notes for staff (not public).", null=True
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_performed_on",
                    models.DateField(
                        blank=True, help_text="Date they performed at our venue.", null=True
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, help_text="Optional <title> override.", max_length=70
                    ),
                ),
                (
                    "seo_title_en",
                    models.CharField(
                        blank=True, help_text="Optional <title> override.", max_length=70, null=True
                    ),
                ),
                (
                    "seo_title_es",
                    models.CharField(
                        blank=True, help_text="Optional <title> override.", max_length=70, null=True
                    ),
                ),
                (
                    "seo_title_de",
                    models.CharField(
                        blank=True, help_text="Optional <title> override.", max_length=70, null=True
                    ),
                ),
                (
                    "seo_title_fr",
                    models.CharField(
                        blank=True, help_text="Optional <title> override.", max_length=70, null=True
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(blank=True, help_text="Meta description.", max_length=160),
                ),
                (
                    "seo_description_en",
                    models.CharField(
                        blank=True, help_text="Meta description.", max_length=160, null=True
                    ),
                ),
                (
                    "seo_description_es",
                    models.CharField(
                        blank=True, help_text="Meta description.", max_length=160, null=True
                    ),
                ),
                (
                    "seo_description_de",
                    models.CharField(
                        blank=True, help_text="Meta description.", max_length=160, null=True
                    ),
                ),
                (
                    "seo_description_fr",
                    models.CharField(
                        blank=True, help_text="Meta description.", max_length=160, null=True
                    ),
                ),
                (
                    "og_image_override",
                    models.ImageField(blank=True, null=True, upload_to="bands/og/"),
                ),
                ("website", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("facebook", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
                ("bandcamp", models.URLField(blank=True)),
                ("soundcloud", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
