# Generated by Django 5.2.8 on 2025-11-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bands", "0002_alter_band_name_de_alter_band_name_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="genre",
            field=models.CharField(
                blank=True,
                help_text="Music style (e.g., techno, indie rock).",
                max_length=120,
            ),
        ),
    ]

